### ISSUE TITLE
this quicklook plugin hardly works for me

### ISSUE THREAD

**Issue by zhangyoufu** [jendas1/jupyter-notebook-quick-look#1]
OS: El Capitan 10.11.3
1. Tried to put this plugin in ~/Library/QuickLook and /Library/QuickLook, don't work. It seems that file extension `.ipynb` is not registered as UTI `public.ipynb` on my system
2. Tested with `qlmanage`. I can confirm that the generated html looks good, but `qlmanage` doesn't show anything and just stuck there
   
   $ qlmanage -c public.ipynb -p ~/Documents/Untitled.ipynb
   Testing Quick Look preview with files:
       /Users/user/Documents/Untitled.ipynb
       - force using content type UTI: public.ipynb
   [NbConvertApp] Converting notebook /Users/user/Documents/Untitled.ipynb to html
   [NbConvertApp] Writing 221137 bytes to /tmp/3A9253E7-9F38-4AF1-907B-2E823E2B35DA.html
   2016-02-28 14:17:54.138 qlmanage[11064:491373] **\* CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9903, name = 'com.apple.CFPasteboardClient'
   See /usr/include/servers/bootstrap_defs.h for the error codes.
   2016-02-28 14:17:54.139 qlmanage[11064:491373] void __CFPasteboardSetup() : Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions
   ^C

**Comment by jendas1** [comment]
I've updated the code. Can you try it if it works for you? Please delete the quicklook plugin in ~/Library/QuickLook and keep the plugin only in /Library/QuickLook.

**Comment by zhangyoufu** [comment]
It works pretty good. Thank you!
