### ISSUE TITLE
QuickLook plugin doesn't work without the Jupyter app

### ISSUE THREAD

**Issue by lericson** [jendas1/jupyter-notebook-quick-look#3]
It appears that the app needs to be installed when OS X is determining the universal type identifier, the _UTI_ -- not to be confused with the medical abbreviation for urinary tract infection. This is likely because the app associates itself with `*.ipynb` files, then assigns a UTI to it, and then QuickLook uses that to determine which plugin to use.

**Comment by jendas1** [comment]
Did you drop the qlgenerator into /Library/Quicklook and not into ~/Library/QuickLook? Even the generator declares UTI for .ipynb but the declaration cannot be read by the system if it is in user library folder.

**Comment by lericson** [comment]
You’re right, that was my mistake. Perhaps it would be a good thing to put in the documentation? :)
