### ISSUE TITLE
launch path not accessible

### ISSUE THREAD

**Issue by gzepr** [jendas1/jupyter-notebook-quick-look#4]
Hello,

I'm afraid i can't make it work...
here's the debug with qlmanage:

[DEBUG] Previewing file:///Users/ehu/work/audio/kw/kw_process/ehusession_20juin16_process_radio/process_rawrecordings_radio.ipynb. Content type UTI: org.jupyter.ipynb. Generator used: <QLGenerator /Library/QuickLook/jupyter-notebook-quick-look.qlgenerator>
[DEBUG] Loading <QLGenerator /Library/QuickLook/jupyter-notebook-quick-look.qlgenerator>
[ERROR] Computing 6571367.40974338 raised 'launch path not accessible'
[DEBUG] Thumbnailing process_rawrecordings_radio.ipynb -- file:///Users/ehu/work/audio/kw/kw_process/ehusession_20juin16_process_radio/ - type: org.jupyter.ipynb - generator: <QLGenerator /Library/QuickLook/jupyter-notebook-quick-look.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Users/ehu/work/audio/kw/kw_process/ehusession_20juin16_process_radio/process_rawrecordings_radio.ipynb. Content type UTI: org.jupyter.ipynb. Generator used: <QLGenerator /Library/QuickLook/jupyter-notebook-quick-look.qlgenerator>
[ERROR] Computing 6571367.40974338 raised 'launch path not accessible'

**Comment by jendas1** [comment]
Hi, 
do you have python3 installed? If yes, what returns `which python3` (type it to the terminal)? This generator assumes that python3 executable is located in /usr/local/bin/python3.

**Comment by gzepr** [comment]
Hi,
I use python 2.7:

~$ which python
/Users/ehu/anaconda/bin/python
~$ python --version
Python 2.7.11 :: Anaconda 4.0.0 (x86_64)

**Comment by jendas1** [comment]
You need to have python3 installed (with jupyter). This generator is built just for python3.
