### ISSUE TITLE
version numbers don't match

### ISSUE THREAD

**Issue by core-code** [jendas1/jupyter-notebook-quick-look#8]
i've downloaded version 0.2 from GitHub but after download it claims to already be at version 1.0

the CFBundleShortVersionString in the Info.plist doesn't line-up with the release version

<img width="254" alt="Screenshot 2020-10-29 at 11 29 05" src="https://user-images.githubusercontent.com/1261954/97556667-0d33de00-19da-11eb-935b-fb9de71b5a12.png">

**Comment by jendas1** [comment]
Thanks, it is fixed now.

**Comment by core-code** [comment]
awesome, thanks!
